
name: Run integration tests againt Gaffer deployed On Kind

# Controls when the action will run. 
on:
  workflow_dispatch:
  # Triggers the workflow to run every day at 0920
  schedule:
  - cron: "20 9 * * *"
defaults:
  run:
    working-directory: store-implementation/accumulo-store/src/test/resources
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs script to to execute bash commands in kind-deployment.md 
      - name: Update properties files #1
        run: sed '16 a gaffer.store.properties.class=uk.gov.gchq.gaffer.accumulostore.AccumuloProperties' store.properties
      - name: Update properties files #2 
        run: sed -i 's/localhost/localhost:58630/g' store.properties
      - name: Update properties files #3 
        run: sed -i 's/user/root/g' store.properties
      - name: Update properties files #4 
        run: sed -i 's/standardInstance/instance/g' store.properties
      - name: Update properties files #5
        run: sed -i 's/localhost/localhost:58630/g' store2.properties
      - name: Update properties files #6 
        run: sed -i 's/user/root/g' store2.properties
      - name: Update properties files #7 
        run: sed -i 's/standardInstance/instance/g' store2.properties
      - name: Update properties files #8 
        run: sed -i 's/localhost/localhost:58630/g' accumuloStoreClassicKeys.properties
      - name: Update properties files #9 
        run: sed -i 's/user/root/g' accumuloStoreClassicKeys.properties
      - name: Update properties files #10 
        run: sed -i 's/standardInstance/instance/g' accumuloStoreClassicKeys.properties
      - name: Update properties files #11 
        run: sed '16 a gaffer.store.accumulo.keypackage.class=uk.gov.gchq.gaffer.accumulostore.key.core.impl.classic.ClassicKeyPackage' accumuloStoreClassicKeys.properties 
      - name: Run the integration tests
        run: cd ../../.. mvn verify
      - name: Send success message to ms teams
        if: ${{ success() }}
        uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
        with:
           webhook: 'https://<ad9b000a.gchq.gov.uk@emea.teams.ms>'
           message: 'Tests have passed'
      - name: Send failure message to ms teams
        if: ${{ failure() }}
        uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
        with:
           webhook: 'https://outlook.office.com/webhook/<some_giant_id>'
           message: 'Tests have failed'
