
name: Run integration tests againt Gaffer deployed On Kind

# Controls when the action will run. 
on:
  workflow_dispatch:
  # Triggers the workflow to run every day at 0920
  schedule:
  - cron: "20 9 * * *"
defaults:
  run:
    working-directory: store-implementation/accumulo-store/src/test/resources
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs script to to execute bash commands in kind-deployment.md 
      - name: Update properties files
        run: sed '16 a gaffer.store.properties.class=uk.gov.gchq.gaffer.accumulostore.AccumuloProperties' store.properties
            
      - name: Run the integration tests
        run: mvn verify
      - name: Send success message to ms teams
        if: ${{ success() }}
        uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
        with:
           webhook: 'https://<ad9b000a.gchq.gov.uk@emea.teams.ms>'
           message: 'Tests have passed'
      - name: Send failure message to ms teams
        if: ${{ failure() }}
        uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
        with:
           webhook: 'https://outlook.office.com/webhook/<some_giant_id>'
           message: 'Tests have failed'
